In [2]:
import numpy as np

# Creating a Numpy Array

In [6]:
# Creating a rank 1 Array
arr1d = np.array([1, 2, 3])
print(arr1d)

# Creating a rank 2 Array
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])
print(arr2d)

# Creating an array from tuple
arr3 = np.array((1, 3, 2))
print(arr3)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[1 3 2]


# NumPy Array Indexing

In [7]:
# Single element access
print("Single element access:", arr1d[2])  

# Negative indexing
print("Negative indexing:", arr1d[-1])  

# Multidimensional array access
print("Multidimensional array access:", arr2d[1, 0])

Single element access: 3
Negative indexing: 3
Multidimensional array access: 4


In [8]:
#elements from index 1 to 3
print("Range of Elements:",arr2d[1:4])

#all rows, second column
print("Multidimensional Slicing:", arr2d[:, 1])

Range of Elements: [[4 5 6]]
Multidimensional Slicing: [2 5]


In [9]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Integer array indexing 
indices = np.array([1, 3, 5])
print ("Integer array indexing:", arr[indices])

# boolean array indexing 
cond = arr > 0
print ("\nElements greater than 0:\n", arr[cond])

Integer array indexing: [20 40 60]

Elements greater than 0:
 [ 10  20  30  40  50  60  70  80  90 100]


# NumPy Basic Operations

In [14]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Addition
add = x + y  
print("Addition:",add)

# Subtraction
subtract = x - y 
print("substration:",subtract)

# Multiplication
multiply = x * y 
print("multiplication:",multiply)

# Division
divide = x / y  
print("division:", divide)

Addition: [5 7 9]
substration: [-3 -3 -3]
multiplication: [ 4 10 18]
division: [0.25 0.4  0.5 ]


In [11]:
# Applying a unary operation: absolute value
result = np.absolute(x)
print("Absolute value:", result)

Absolute value: [1 2 3]


In [16]:
# Applying a binary operation: addition
result = np.add(x, y)

print("Array 1:", x)
print("Array 2:", y)
print("Addition Result:", result)

Array 1: [1 2 3]
Array 2: [4 5 6]
Addition Result: [5 7 9]


# NumPy ufuncs

In [17]:
# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))

# exponential values
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))

# square root of array values
print ("Square root of array elements:", np.sqrt(a))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


# NumPy Sorting Arrays

In [18]:
# set alias names for dtypes
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]

# Values to be put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7), 
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]
           
# Creating array
arr = np.array(values, dtype = dtypes)
print ("\nArray sorted by names:\n",
            np.sort(arr, order = 'name'))
            
print ("Array sorted by graduation year and then cgpa:\n",
                np.sort(arr, order = ['grad_year', 'cgpa']))


Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by graduation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


# Initialize a Python NumPy Array Using Special Functions

### NumPy provides several built-in functions to generate arrays with specific properties.
- np.zeros(): Creates an array filled with zeros.
- np.ones(): Creates an array filled with ones.
- np.full(): Creates an array filled with a specified value.
- np.arange(): Creates an array with values that are evenly spaced within a given range.
- np.linspace(): Creates an array with values that are evenly spaced over a specified interval.

In [19]:
zeros_array = np.zeros((2, 3))
ones_array = np.ones((3, 3))
constant_array = np.full((2, 2), 7)
range_array = np.arange(0, 10, 2)  # start, stop, step
linspace_array = np.linspace(0, 1, 5)  # start, stop, num

print("Zero Array:","\n",zeros_array)
print("Ones Array:","\n",ones_array)
print("Constant Array:","\n",constant_array)
print("Range Array:","\n",range_array)
print("Linspace Array:","\n",linspace_array)

Zero Array: 
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Constant Array: 
 [[7 7]
 [7 7]]
Range Array: 
 [0 2 4 6 8]
Linspace Array: 
 [0.   0.25 0.5  0.75 1.  ]


# Create Python Numpy Arrays Using Random Number Generation
### NumPy provides functions to create arrays filled with random numbers.
- np.random.rand(): Creates an array of specified shape and fills it with random values sampled from a uniform distribution over [0, 1).
- np.random.randn(): Creates an array of specified shape and fills it with random values sampled from a standard normal distribution.
- np.random.randint(): Creates an array of specified shape and fills it with random integers within a given range.

In [20]:
random_array = np.random.rand(2, 3)
normal_array = np.random.randn(2, 2)
randint_array = np.random.randint(1, 10, size=(2, 3))  

print(random_array)
print(normal_array)
print(randint_array)

[[0.76416444 0.13031077 0.25804382]
 [0.44539892 0.66991682 0.82282753]]
[[-0.50805948 -0.58740569]
 [-0.4264366   0.25525098]]
[[6 8 9]
 [3 5 7]]


# Create Python Numpy Arrays Using Matrix Creation Routines
### NumPy provides functions to create specific types of matrices.
- np.eye(): Creates an identity matrix of specified size.
- np.diag(): Constructs a diagonal array.
- np.zeros_like(): Creates an array of zeros with the same shape and type as a given array.
- np.ones_like(): Creates an array of ones with the same shape and type as a given array.

In [21]:
identity_matrix = np.eye(3)
diagonal_array = np.diag([1, 2, 3])
zeros_like_array = np.zeros_like(diagonal_array)
ones_like_array = np.ones_like(diagonal_array)

print(identity_matrix)
print(diagonal_array)
print(zeros_like_array)
print(ones_like_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


# Reshape NumPy Array

In [22]:
# creating a numpy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

# printing array
print("Array : " + str(array))

# length of array
n = array.size

# N-D array N dimension
N = 4

# calculating M
M = n//N

# reshaping numpy array
# converting it to 2-D from 1-D array
reshaped1 = array.reshape((N, M))

# printing reshaped array
print("First Reshaped Array : ")
print(reshaped1)

# creating another reshaped array
reshaped2 = np.reshape(array, (2, 8))

# printing reshaped array
print("Second Reshaped Array : ")
print(reshaped2)

Array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
First Reshaped Array : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Second Reshaped Array : 
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [23]:
# creating a numpy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

# printing array
print("Array : " + str(array))


# reshaping numpy array
# converting it to 3-D from 1-D array
reshaped = array.reshape((2, 2, 4))

# printing reshaped array
print("Reshaped 3-D Array : ")
print(reshaped)

Array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Reshaped 3-D Array : 
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


# Numpy numpy.resize()

In [24]:
# Making a random array
gfg = np.array([1, 2, 3, 4, 5, 6])

# Required values 12, existing values 6
gfg.resize(3, 4)

print(gfg)

[[1 2 3 4]
 [5 6 0 0]
 [0 0 0 0]]


# numpy.stack()

In [26]:
# input array
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stacking 2 1-d arrays
c = np.stack((a, b),axis=0)
print(c)
# stack 2 1-d arrays column-wise
d = np.stack((a,b),axis=1)
print(d)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


# NumPy Splitting Array

- Split numpy array using numpy.split()
- Split numpy array using numpy.array_split()
- Splitting NumPy 2D Arrays
- Split numpy array using numpy.vsplit()
- Split numpy array using numpyhsplit()
- Split numpy arrayusing numpy.dsplit()

In [29]:
Arr1 = np.array([1, 2, 3, 4, 5, 6])
array = np.array_split(Arr1, 3)
print(array)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [31]:
# Creating an example array
array = np.arange(6)

# Splitting the array into 2 equal parts along the first axis (axis=0)
result = np.split(array, 2)

print("Array:")
print(array)
print("\nResult after numpy.split():")
print(result)

# Splitting the array into 4 unequal parts along the first axis (axis=0)
result = np.array_split(array, 4)

print("\nResult after numpy.array_split():")
print(result)

Array:
[0 1 2 3 4 5]

Result after numpy.split():
[array([0, 1, 2]), array([3, 4, 5])]

Result after numpy.array_split():
[array([0, 1]), array([2, 3]), array([4]), array([5])]


In [32]:
# Creating a 2D array
array = np.array([[3, 2, 1], [8, 9, 7], [4, 6, 5]])

# Splitting the array into 3 equal parts along the second axis (axis=1)
result = np.split(array, 3, axis=1)

print("2D Array:")
print(array)
print("\nResult after numpy.split() along axis=1:")
print(result)

2D Array:
[[3 2 1]
 [8 9 7]
 [4 6 5]]

Result after numpy.split() along axis=1:
[array([[3],
       [8],
       [4]]), array([[2],
       [9],
       [6]]), array([[1],
       [7],
       [5]])]


In [33]:
# Creating an example matrix
matrix = np.array([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9],
                            [10, 11, 12]])

# Vertical splitting into 2 subarrays along axis=0
result = np.vsplit(matrix, 2)

print("Matrix:")
print(matrix)
print("\nResult after numpy.vsplit():")
print(result)

Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Result after numpy.vsplit():
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


In [35]:
result = np.hsplit(matrix, 3)

print("2D Array:")
print(matrix)
print("\nResult after numpy.hsplit():")
print(result)

2D Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Result after numpy.hsplit():
[array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]])]


In [36]:
original_3d_array = np.arange(24).reshape((2, 3, 4))

# Splitting along axis=2 (third axis)
result = np.dsplit(original_3d_array, 2)

print("Original 3D Array:")
print(original_3d_array)
print("\nResult after numpy.dsplit():")
print(result)

Original 3D Array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Result after numpy.dsplit():
[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])]


# NumPy Array Broadcasting

In [37]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])  
scalar = 10  

result = array_2d + scalar
print(result)

[[11 12 13]
 [14 15 16]]


In [38]:
a1 = np.array([2, 4, 6])
a2 = np.array([[1, 3, 5], [7, 9, 11]])
res = a1 + a2
print(res)

[[ 3  7 11]
 [ 9 13 17]]


In [39]:
ages = np.array([12, 24, 35, 45, 60, 72])

age_group = np.array(["Adult", "Minor"])

result = np.where(ages > 18, age_group[0], age_group[1])

print(result)

['Minor' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']


In [ ]:
class Company:
    company_name = "TechNova"

    def __init__(self, name):
        self.name = name  # instance variable

    @staticmethod
    def format_employee_name(first_name, last_name):
        """
        Static method: Doesn't depend on class or instance.
        It only formats and returns a name string.
        """
        return f"{first_name} {last_name}".title()

    @classmethod
    def from_full_name(cls, full_name):
        """
        Class method: Receives the class as the first argument.
        Creates a Company object by extracting the first word as 'name'.
        """
        first_name = full_name.split()[0]
        # Calls static method from inside a class method
        formatted_name = cls.format_employee_name(first_name, "Employee")
        return cls(formatted_name)

    def display_info(self):
        """Instance method to show employee info."""
        print(f"Employee: {self.name} | Company: {self.company_name}")


# --- Usage ---
# 1. Calling static method directly
formatted = Company.format_employee_name("john", "doe")
print("Formatted Name:", formatted)  # Output: John Doe

# 2. Calling class method to create an instance
employee_obj = Company.from_full_name("Alice Johnson")

# 3. Displaying employee info
employee_obj.display_info()
