# Python Generators
### In Python, a generator is a function that returns an iterator that produces a sequence of values when iterated over. Generators are useful when we want to produce a large sequence of values, but we don't want to store all of them in memory at once. When the generator function is called, it does not execute the function body immediately. Instead, it returns a generator object that can be iterated over to produce the values.

#### The yield keyword is used to produce a value from the generator and pause the generator function's execution until the next value is requested.

In [3]:
def my_generator(n):
    # initialize counter
    value = 0

    # loop until counter is less than n
    while value < n:
        # produce the current value of the counter
        yield value
        # increment the counter
        value += 1

# iterate over the generator object produced by my_generator
for value in my_generator(3):
    # print each value produced by generator
    print(value)

0
1
2


# Python Generator Expression

### It is similar to a list comprehension, but instead of creating a list, it creates a generator object that can be iterated over to produce the values in the generator.

In [6]:
# create the generator object
squares_generator = (i * i for i in range(5))

# iterate over the generator and print the values
for i in squares_generator:
    print(i)

0
1
4
9
16


# Using Advanced Generator Methods

### 1. .send(value)
- Used to send a value INTO a generator at the point where it paused at a yield.
- Also resumes execution of the generator.
- The yield expression receives the sent value.

In [7]:
def gen():
    value = yield "Start"
    print("Received:", value)

g = gen()
print(next(g))         # Start (pauses at yield)
g.send("Hello")        # Resumes and prints: Received: Hello


Start
Received: Hello


StopIteration: 

### 2. .throw(type, value=None, traceback=None)
- Used to raise an exception inside the generator at the current yield expression.
- The generator can catch that exception and handle it.
- If it's not handled, the generator stops with an error.

In [9]:
def gen():
    try:
        yield
    except ValueError:
        print("ValueError caught")

g = gen()
next(g)               # Start the generator
g.throw(ValueError)   # Raises inside the generator and is caught


ValueError caught


StopIteration: 

### 3. .close()
- Tells the generator to stop execution.
- Raises GeneratorExit inside the generator.
- Use this to gracefully terminate a generator early.

In [11]:
def gen():
    try:
        while True:
            yield
    except GeneratorExit:
        print("Generator closed")

g = gen()
next(g)        # Start the generator
g.close()      # Prints: Generator closed


Generator closed


# Decorators in Python

### decorators are a powerful and flexible way to modify or extend the behavior of functions or methods, without changing their actual code.
- A decorator is essentially a function that takes another function as an argument and returns a new function with enhanced functionality.

In [12]:
# A simple decorator function
def decorator(func):
  
    def wrapper():
        print("Before calling the function.")
        func()
        print("After calling the function.")
    return wrapper

# Applying the decorator to a function
@decorator

def greet():
    print("Hello, World!")

greet()

Before calling the function.
Hello, World!
After calling the function.


## Types of Decorators

### 1. Function Decorators:
- The most common type of decorator, which takes a function as input and returns a new function.

In [13]:
def simple_decorator(func):
    def wrapper():
        print("Before calling the function.")
        func()
        print("After calling the function.")
    return wrapper

@simple_decorator
def greet():
    print("Hello, World!")

greet()

Before calling the function.
Hello, World!
After calling the function.


### 2. Method Decorators:
- Used to decorate methods within a class. They often handle special cases, such as the self argument for instance methods.

In [14]:
def method_decorator(func):
    def wrapper(self, *args, **kwargs):
        print("Before method execution")
        res = func(self, *args, **kwargs)
        print("After method execution")
        return res
    return wrapper

class MyClass:
    @method_decorator
    def say_hello(self):
        print("Hello!")

obj = MyClass()
obj.say_hello()

Before method execution
Hello!
After method execution


### 3. Class Decorators
- Class decorators are used to modify or enhance the behavior of a class. Like function decorators, class decorators are applied to the class definition. They work by taking the class as an argument and returning a modified version of the class.

In [15]:
def fun(cls):
    cls.class_name = cls.__name__
    return cls

@fun
class Person:
    pass

print(Person.class_name)

Person


## Common Built-in Decorators in Python

### @staticmethod
- The @staticmethod decorator is used to define a method that doesn't operate on an instance of the class (i.e., it doesn't use self).

In [16]:
class MathOperations:
    @staticmethod
    def add(x, y):
        return x + y

# Using the static method  ,,
res = MathOperations.add(5, 3)
print(res)

8


### @classmethod
- The @classmethod decorator is used to define a method that operates on the class itself (i.e., it uses cls). 

In [18]:
class Employee:
    raise_amount = 1.05

    def __init__(self, name, salary):
        self.name = name
        self.salary = salary

    @classmethod
    def set_raise_amount(cls, amount):
        cls.raise_amount = amount

# Using the class method
Employee.set_raise_amount(1.10)
print(Employee.raise_amount)

1.1


### @property
- The @property decorator is used to define a method as a property, which allows you to access it like an attribute. 

In [19]:
class Circle:
    def __init__(self, radius):
        self._radius = radius

    @property
    def radius(self):
        return self._radius

    @radius.setter
    def radius(self, value):
        if value >= 0:
            self._radius = value
        else:
            raise ValueError("Radius cannot be negative")

    @property
    def area(self):
        return 3.14159 * (self._radius ** 2)

# Using the property
c = Circle(5)
print(c.radius) 
print(c.area)    
c.radius = 10
print(c.area)

5
78.53975
314.159


# Deep Copy and Shallow Copy

In [23]:
import copy

a = [[1, 2, 3], [4, 5, 6]]

# Creating a deep copy of the nested list 'a'
b = copy.deepcopy(a)

# Modifying an element in the deep-copied list
b[0][0] = 99 
print(a)

[[1, 2, 3], [4, 5, 6]]


In [24]:
import copy  

a = [[1, 2, 3], [4, 5, 6]]

# Creating a shallow copy of the nested list 'original'
b = copy.copy(a)

# Modifying an element in the shallow-copied list
b[0][0] = 99

# Printing the original and shallow-copied lists  
print(a)

[[99, 2, 3], [4, 5, 6]]


# Random Numbers

## 1. Pseudorandom Number Generators

In [25]:
import random

# Set the seed for reproducibility
random.seed(123)  # Try changing this number or removing it

# Simulate rolling a 6-sided die 5 times
for i in range(5):
    roll = random.randint(1, 6)
    print(f"Roll {i+1}: {roll}")

Roll 1: 1
Roll 2: 3
Roll 3: 1
Roll 4: 4
Roll 5: 3


## 2. Random Numbers with the Python Standard Library

In [27]:
from random import seed
from random import random
# seed random number generator
seed(1)
# generate some random numbers
print(random(), random(), random())
# reset the seed
seed(1)
# generate some random numbers
print(random(), random(), random())

0.13436424411240122 0.8474337369372327 0.763774618976614
0.13436424411240122 0.8474337369372327 0.763774618976614


In [29]:
from random import randint
seed(1)
# generate some integers
for _ in range(10):
	value = randint(0, 10)
	print(value)

2
9
1
4
1
7
7
7
10
6


In [30]:
from random import choice
# seed random number generator
seed(1)
# prepare a sequence
sequence = [i for i in range(20)]
print(sequence)
# make choices from the sequence
for _ in range(5):
	selection = choice(sequence)
	print(selection)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
4
18
2
8
3


In [31]:
from random import sample
# seed random number generator
seed(1)
# prepare a sequence
sequence = [i for i in range(20)]
print(sequence)
# select a subset without replacement
subset = sample(sequence, 5)
print(subset)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[4, 18, 2, 8, 3]


In [32]:
from random import shuffle
# seed random number generator
seed(1)
# prepare a sequence
sequence = [i for i in range(20)]
print(sequence)
# randomly shuffle the sequence
shuffle(sequence)
print(sequence)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[11, 5, 17, 19, 9, 0, 16, 1, 15, 6, 10, 13, 14, 12, 7, 3, 8, 2, 18, 4]


## 3. Random Numbers with NumPy

In [34]:
from random import seed
from numpy.random import rand
# seed random number generator
seed(1)
# generate random numbers between 0-1
values = rand(10)
print(values)

[0.25554513 0.79348338 0.48375135 0.36772626 0.27583461 0.39797894
 0.61860738 0.31950678 0.44189459 0.19635484]


In [35]:
# generate random integer values
from numpy.random import seed
from numpy.random import randint
# seed random number generator
seed(1)
# generate some integers
values = randint(0, 10, 20)
print(values)

[5 8 9 5 0 0 1 7 6 9 2 4 5 2 4 2 4 7 7 9]


In [36]:
# randomly shuffle a sequence
from numpy.random import seed
from numpy.random import shuffle
# seed random number generator
seed(1)
# prepare a sequence
sequence = [i for i in range(20)]
print(sequence)
# randomly shuffle the sequence
shuffle(sequence)
print(sequence)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[3, 16, 6, 10, 2, 14, 4, 17, 7, 1, 13, 0, 19, 18, 9, 15, 8, 12, 11, 5]


# NumPy

In [37]:
%pip install numpy


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [40]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [42]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [43]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [44]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [45]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [50]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[2 4]
[1 3 5 7]


In [60]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])
print(arr.shape)

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]
(2, 5)


In [54]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [55]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [59]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [61]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [62]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [63]:
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [64]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [68]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [69]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [70]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [71]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [74]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7,  side='right')

print(x)

2


In [75]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [76]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [77]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [79]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


# Pandas

In [3]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)

0    1
1    7
2    2
dtype: int64


#### With the index argument, you can name your own labels.

In [4]:
a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

x    1
y    7
z    2
dtype: int64


In [5]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

myvar = pd.DataFrame(data)

print(myvar)

   calories  duration
0       420        50
1       380        40
2       390        45


In [6]:
print(myvar.loc[[0, 1]])

   calories  duration
0       420        50
1       380        40


In [7]:
print(pd.options.display.max_rows) 

60


# multiprocessing — Process-based parallelism

In [11]:
%pip install multiprocess

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [multiprocess] [multiprocess]

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [12]:
from multiprocess import Pool

def f(x):
    return x * x

with Pool(3) as p:
    print(p.map(f, [1, 2, 3]))

[1, 4, 9]


In [17]:
%pip install multiprocess


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [18]:
from multiprocess import Process

def f(name):
    print('hello', name)

if __name__ == '__main__':
    p = Process(target=f, args=('bob',))
    p.start()
    p.join()

hello bob


In [19]:
from multiprocess import Process
import os

def info(title):
    print(title)
    print('module name:', __name__)
    print('parent process:', os.getppid())
    print('process id:', os.getpid())

def f(name):
    info('function f')
    print('hello', name)

if __name__ == '__main__':
    info('main line')
    p = Process(target=f, args=('bob',))
    p.start()
    p.join()

main line
module name: __main__
parent process: 4893
process id: 5064
function f
module name: __main__
parent process: 5064
process id: 5782
hello bob


In [20]:
import multiprocess

def square_list(mylist, result, square_sum):
    """
    function to square a given list
    """
    # append squares of mylist to result array
    for idx, num in enumerate(mylist):
        result[idx] = num * num

    # square_sum value
    square_sum.value = sum(result)

    # print result Array
    print("Result(in process p1): {}".format(result[:]))

    # print square_sum Value
    print("Sum of squares(in process p1): {}".format(square_sum.value))

if __name__ == "__main__":
    # input list
    mylist = [1,2,3,4]

    # creating Array of int data type with space for 4 integers
    result = multiprocess.Array('i', 4)

    # creating Value of int data type
    square_sum = multiprocess.Value('i')

    # creating new process
    p1 = multiprocess.Process(target=square_list, args=(mylist, result, square_sum))

    # starting process
    p1.start()

    # wait until the process is finished
    p1.join()

    # print result array
    print("Result(in main program): {}".format(result[:]))

    # print square_sum Value
    print("Sum of squares(in main program): {}".format(square_sum.value))

Result(in process p1): [1, 4, 9, 16]
Sum of squares(in process p1): 30
Result(in main program): [1, 4, 9, 16]
Sum of squares(in main program): 30


In [21]:
import multiprocess

def print_records(records):
    
    for record in records:
        print("Name: {0}\nScore: {1}\n".format(record[0], record[1]))

def insert_record(record, records):

    records.append(record)
    print("New record added!\n")

if __name__ == '__main__':
    with multiprocess.Manager() as manager:
        # creating a list in server process memory
        records = manager.list([('Sam', 10), ('Adam', 9), ('Kevin',9)])
        # new record to be inserted in records
        new_record = ('Jeff', 8)

        # creating new processes
        p1 = multiprocess.Process(target=insert_record, args=(new_record, records))
        p2 = multiprocess.Process(target=print_records, args=(records,))

        # running process p1 to insert new record
        p1.start()
        p1.join()

        # running process p2 to print records
        p2.start()
        p2.join()

New record added!

Name: Sam
Score: 10

Name: Adam
Score: 9

Name: Kevin
Score: 9

Name: Jeff
Score: 8



In [22]:
import multiprocess

def square_list(mylist, q):
    # append squares of mylist to queue
    for num in mylist:
        q.put(num * num)

def print_queue(q):
    print("Queue elements:")
    while not q.empty():
        print(q.get())
    print("Queue is now empty!")

if __name__ == "__main__":
    # input list
    mylist = [1,2,3,4]

    # creating multiprocessing Queue
    q = multiprocess.Queue()

    # creating new processes
    p1 = multiprocess.Process(target=square_list, args=(mylist, q))
    p2 = multiprocess.Process(target=print_queue, args=(q,))

    # running process p1 to square list
    p1.start()
    p1.join()

    # running process p2 to get queue elements
    p2.start()
    p2.join()

Queue elements:
1
4
9
16
Queue is now empty!


In [26]:
import multiprocess
def sender(conn, msgs):
    for msg in msgs:
        conn.send(msg)
        print("Sent the message: {}".format(msg))
    conn.close()

def receiver(conn):
    while 1:
        msg = conn.recv()
        if msg == "END":
            break
        print("Received the message: {}".format(msg))

if __name__ == "__main__":
    # messages to be sent
    msgs = ["hello", "hey", "hru?", "END"]

    # creating a pipe
    parent_conn, child_conn = multiprocess.Pipe()

    # creating new processes
    p1 = multiprocess.Process(target=sender, args=(parent_conn,msgs))
    p2 = multiprocess.Process(target=receiver, args=(child_conn,))
    

    # running processes
    p1.start()
    p2.start()

    # wait until processes finish
    p1.join()
    p2.join()

Sent the message: hello
Sent the message: heyReceived the message: hello

Sent the message: hru?Received the message: hey

Sent the message: END
Received the message: hru?


In [27]:
# Python program to illustrate 
# the concept of locks
# in multiprocessing
import multiprocess

# function to withdraw from account
def withdraw(balance, lock):    
    for _ in range(10000):
        lock.acquire()
        balance.value = balance.value - 1
        lock.release()

# function to deposit to account
def deposit(balance, lock):    
    for _ in range(10000):
        lock.acquire()
        balance.value = balance.value + 1
        lock.release()

def perform_transactions():

    # initial balance (in shared memory)
    balance = multiprocess.Value('i', 100)

    # creating a lock object
    lock = multiprocess.Lock()

    # creating new processes
    p1 = multiprocess.Process(target=withdraw, args=(balance,lock))
    p2 = multiprocess.Process(target=deposit, args=(balance,lock))

    # starting processes
    p1.start()
    p2.start()

    # wait until processes are finished
    p1.join()
    p2.join()

    # print final balance
    print("Final balance = {}".format(balance.value))

if __name__ == "__main__":
    for _ in range(10):

        # perform same transaction process 10 times
        perform_transactions()

Final balance = 100
Final balance = 100
Final balance = 100
Final balance = 100
Final balance = 100
Final balance = 100
Final balance = 100
Final balance = 100
Final balance = 100
Final balance = 100


In [28]:
# Python program to understand 
# the concept of pool
import multiprocess
import os

def square(n):
    print("Worker process id for {0}: {1}".format(n, os.getpid()))
    return (n*n)

if __name__ == "__main__":
    # input list
    mylist = [1,2,3,4,5]

    # creating a pool object
    p = multiprocess.Pool()

    # map list to target function
    result = p.map(square, mylist)

    print(result)

Worker process id for 1: 5988Worker process id for 2: 5989Worker process id for 3: 5990Worker process id for 4: 5991Worker process id for 5: 5992

[1, 4, 9, 16, 25]





# threading — Thread-based parallelism

In [29]:
import threading

In [31]:
def print_cube(num):
    print("Cube: {}" .format(num * num * num))


def print_square(num):
    print("Square: {}" .format(num * num))


if __name__ =="__main__":
    t1 = threading.Thread(target=print_square, args=(10,))
    t2 = threading.Thread(target=print_cube, args=(10,))

    t1.start()
    t2.start()

    t1.join()
    t2.join()

    print("Done!")

Square: 100
Cube: 1000
Done!


In [32]:
def task1():
    print("Task 1 assigned to thread: {}".format(threading.current_thread().name))
    print("ID of process running task 1: {}".format(os.getpid()))

def task2():
    print("Task 2 assigned to thread: {}".format(threading.current_thread().name))
    print("ID of process running task 2: {}".format(os.getpid()))

if __name__ == "__main__":

    print("ID of process running main program: {}".format(os.getpid()))

    print("Main thread name: {}".format(threading.current_thread().name))

    t1 = threading.Thread(target=task1, name='t1')
    t2 = threading.Thread(target=task2, name='t2')

    t1.start()
    t2.start()

    t1.join()
    t2.join()

ID of process running main program: 5064
Main thread name: MainThread
Task 1 assigned to thread: t1
ID of process running task 1: 5064
Task 2 assigned to thread: t2
ID of process running task 2: 5064


In [33]:
import concurrent.futures

def worker():
    print("Worker thread running")

pool = concurrent.futures.ThreadPoolExecutor(max_workers=2)

pool.submit(worker)
pool.submit(worker)

pool.shutdown(wait=True)

print("Main thread continuing to run")

Worker thread running
Worker thread running
Main thread continuing to run


In [34]:
# global variable x
x = 0

def increment():
    """
    function to increment global variable x
    """
    global x
    x += 1

def thread_task(lock):
    """
    task for thread
    calls increment function 100000 times.
    """
    for _ in range(100000):
        lock.acquire()
        increment()
        lock.release()

def main_task():
    global x
    # setting global variable x as 0
    x = 0

    # creating a lock
    lock = threading.Lock()

    # creating threads
    t1 = threading.Thread(target=thread_task, args=(lock,))
    t2 = threading.Thread(target=thread_task, args=(lock,))

    # start threads
    t1.start()
    t2.start()

    # wait until threads finish their job
    t1.join()
    t2.join()

if __name__ == "__main__":
    for i in range(10):
        main_task()
        print("Iteration {0}: x = {1}".format(i,x))

Iteration 0: x = 200000
Iteration 1: x = 200000
Iteration 2: x = 200000
Iteration 3: x = 200000
Iteration 4: x = 200000
Iteration 5: x = 200000
Iteration 6: x = 200000
Iteration 7: x = 200000
Iteration 8: x = 200000
Iteration 9: x = 200000


# Async/Await in Python

In [37]:
import asyncio

async def task_1():
    print("Task 1 started")
    await asyncio.sleep(2)  # Simulate a 2-second task
    print("Task 1 completed")

async def task_2():
    print("Task 2 started")
    await asyncio.sleep(1)  # Simulate a 1-second task
    print("Task 2 completed")

async def main():
    await asyncio.gather(task_1(), task_2())  # Run both tasks concurrently

await main()

Task 1 started
Task 2 started
Task 2 completed
Task 1 completed


In [39]:
import asyncio

async def fn():
    print('This is ')
    await asyncio.sleep(1)
    print('asynchronous programming')
    await asyncio.sleep(1)
    print('and not multi-threading')

await fn()

This is 
asynchronous programming
and not multi-threading


In [40]:
async def fn():
    
    print("one")
    await asyncio.sleep(1)
    await fn2()
    print('four')
    await asyncio.sleep(1)
    print('five')
    await asyncio.sleep(1)

async def fn2():
    await asyncio.sleep(1)
    print("two")
    await asyncio.sleep(1)
    print("three")
await fn()

one
two
three
four
five


# Abstract Base Classes in Python

In [42]:
from abc import ABC, abstractmethod

# Define an abstract class
class Animal(ABC):
    
    @abstractmethod
    def sound(self):
        pass  # This is an abstract method, no implementation here.

# Concrete subclass of Animal
class Dog(Animal):
    
    def sound(self):
        return "Bark"  # Providing the implementation of the abstract method

# Create an instance of Dog
dog = Dog()
print(dog.sound())  # Output: Bark

Bark


# Dependency Injection in Python


In [44]:
class EmailService:
    def send_email(self, message):
        print(f"Sending email: {message}")
class UserController:
    def __init__(self):
        self.email_service = EmailService()  # Hard dependency
    def register_user(self, username):
        print(f"Registering user: {username}")
        self.email_service.send_email(f"Welcome, {username}!")

In [45]:
class EmailService:
    def send_email(self, message):
        print(f"Sending email: {message}")
class UserController:
    def __init__(self, email_service):
        self.email_service = email_service  # Injected dependency
    def register_user(self, username):
        print(f"Registering user: {username}")
        self.email_service.send_email(f"Welcome, {username}!")
# Inject the dependency
email_service = EmailService()
controller = UserController(email_service)

# Factory Method

In [46]:
# Python Code for Object
# Oriented Concepts without
# using Factory method 

class FrenchLocalizer:

    """ it simply returns the french version """

    def __init__(self):

        self.translations = {"car": "voiture", "bike": "bicyclette",
                             "cycle":"cyclette"}

    def localize(self, msg):

        """change the message using translations"""
        return self.translations.get(msg, msg)

class SpanishLocalizer:
    """it simply returns the spanish version"""

    def __init__(self):

        self.translations = {"car": "coche", "bike": "bicicleta",
                             "cycle":"ciclo"}

    def localize(self, msg):

        """change the message using translations"""
        return self.translations.get(msg, msg)

class EnglishLocalizer:
    """Simply return the same message"""

    def localize(self, msg):
        return msg

if __name__ == "__main__":

    # main method to call others
    f = FrenchLocalizer()
    e = EnglishLocalizer()
    s = SpanishLocalizer()

    # list of strings
    message = ["car", "bike", "cycle"]

    for msg in message:
        print(f.localize(msg))
        print(e.localize(msg))
        print(s.localize(msg))

voiture
car
coche
bicyclette
bike
bicicleta
cyclette
cycle
ciclo


In [47]:
# Python Code for factory method 
# it comes under the creational 
# Design Pattern

class FrenchLocalizer:

    """ it simply returns the french version """

    def __init__(self):

        self.translations = {"car": "voiture", "bike": "bicyclette",
                             "cycle":"cyclette"}

    def localize(self, msg):

        """change the message using translations"""
        return self.translations.get(msg, msg)

class SpanishLocalizer:
    """it simply returns the spanish version"""

    def __init__(self):
        self.translations = {"car": "coche", "bike": "bicicleta",
                             "cycle":"ciclo"}

    def localize(self, msg):

        """change the message using translations"""
        return self.translations.get(msg, msg)

class EnglishLocalizer:
    """Simply return the same message"""

    def localize(self, msg):
        return msg

def Factory(language ="English"):

    """Factory Method"""
    localizers = {
        "French": FrenchLocalizer,
        "English": EnglishLocalizer,
        "Spanish": SpanishLocalizer,
    }

    return localizers[language]()

if __name__ == "__main__":

    f = Factory("French")
    e = Factory("English")
    s = Factory("Spanish")

    message = ["car", "bike", "cycle"]

    for msg in message:
        print(f.localize(msg))
        print(e.localize(msg))
        print(s.localize(msg))

voiture
car
coche
bicyclette
bike
bicicleta
cyclette
cycle
ciclo


# List Comprehension 

In [48]:
prices = [1.09, 23.56, 57.84, 4.56, 6.78]
TAX_RATE = .08
def get_price_with_tax(price):
    return price * (1 + TAX_RATE)

final_prices = map(get_price_with_tax, prices)
print(final_prices)

print(list(final_prices))

[1.1772000000000002, 25.4448, 62.467200000000005, 4.9248, 7.322400000000001]


In [49]:
squares = [number * number for number in range(10)]
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [50]:
prices = [1.09, 23.56, 57.84, 4.56, 6.78]
TAX_RATE = .08
def get_price_with_tax(price):
    return price * (1 + TAX_RATE)

final = [get_price_with_tax(price) for price in prices]
final

[1.1772000000000002, 25.4448, 62.467200000000005, 4.9248, 7.322400000000001]

In [53]:
sentence = "the rocket came back from mars"
result = [char for char in sentence if char in "aeiou"]
result

['e', 'o', 'e', 'a', 'e', 'a', 'o', 'a']

In [54]:
original_prices = [1.25, -9.45, 10.22, 3.78, -5.92, 1.16]
[price if price > 0 else 0 for price in original_prices]

[1.25, 0, 10.22, 3.78, 0, 1.16]

In [55]:
quote = "life, uh, finds a way"
{char for char in quote if char in "aeiou"}

{'a', 'e', 'i', 'u'}

In [56]:
%brew update
%brew install pyenv

UsageError: Line magic function `%brew` not found.
